## Experiment 1

## NUMERICAL PYTHON (NUMPY)

##### Amiel Elestin M. Cruz
##### 2ECE-D

### 1. Normalization Problem

In [1]:
import numpy as np 

In [3]:
x = np.random.random((5,5))

In [5]:
print (x)

[[0.15220798 0.93166333 0.29945955 0.96257103 0.96358483]
 [0.55643253 0.72983881 0.81795093 0.36137002 0.91999706]
 [0.84527039 0.04404988 0.18917307 0.96828022 0.71428778]
 [0.11300114 0.4162496  0.00294299 0.59850562 0.6310884 ]
 [0.09778948 0.05146296 0.92810181 0.18071257 0.73463789]]


In [7]:
a = x.mean()

In [9]:
b = x.std()

In [11]:
normal = (x-a)/b

In [13]:
print (normal)

[[-1.09860535  1.17751012 -0.66861079  1.26776478  1.27072523]
 [ 0.08178522  0.58815512  0.84545446 -0.48782381  1.14344303]
 [ 0.92523101 -1.41444171 -0.99066227  1.28443641  0.542744  ]
 [-1.21309465 -0.32756797 -1.53447941  0.20464436  0.2997905 ]
 [-1.25751476 -1.39279449  1.16711    -1.01536808  0.60216906]]


In [15]:
np.save ('X_normalized.npy', normal)

In [33]:
a = np.arange(1,101)
e = np.square (a)
m = e.reshape (10,10)

print(m)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [67]:
c = m [m%3==0]

print (c)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [43]:
np.save ('div_by_3.npy',c)